import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@repo/ds/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
	params
}: {
  children: React.ReactNode;
  params: { locale: string }
}): JSX.Element {
  return (
    <html lang={params.locale}>
      <body className={cn(inter.className)}>{children}</body>
    </html>
  );
}
