import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { cn } from "@repo/ds/utils"
import { ClerkProvider } from "@clerk/nextjs"
import { getTranslations } from "next-intl/server"
import Navbar from "./_components/navbar"

const inter = Inter({ subsets: ["latin"] })

export async function generateMetadata (params: { locale: string }) {
	const t = await getTranslations({ locale: params.locale, namespace: "metadata" })

	return {
		title: t("title"),
		description: "Generated by create turbo",
	} satisfies Metadata
}

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { locale: string };
}): JSX.Element {
	return (
		<html className="h-full" lang={params.locale}>
			<body className={cn(inter.className, "flex flex-col")}>
				<ClerkProvider>
					<Navbar />

					<div>
						{children}
					</div>
				</ClerkProvider>
			</body>
		</html>
	)
}
