name: Pull request code quality

on:
  pull_request:
    branches:
      - dev

jobs:
  quality:
    name: Lint and format code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install

      - name: Verify code quality
        run: bun --bun run verify
        
  test:
    name: Run tests in project
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test --filter=!@scripts/tests

      - name: Run type tests
        run: bun run test:type
        
  envs-preview:
    name: Check preview env integrity
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test --filter=@repo/env
        
  envs-production:
    name: Check production env integrity
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test --filter=@repo/env

  locales:
    name: Test locales information
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run --bun --cwd scripts/tests test